site:
  title: Log Book
  # url: https://avimehenwal.github.io/logbook/
  url: http://127.0.0.1:8080/
  start_page: sample::chapter_4.adoc
  # start_page: work_log::index.adoc

content:
  sources:
  - url: .
    branches: HEAD
    start_path: sample
  - url: .
    branches: HEAD
    start_path: worklog

asciidoc:
  # javascript modules
  extensions:
    - asciidoctor-plantuml
    - asciidoctor-kroki
    - asciidoctor-chart
    - asciidoctor-emoji
    - asciidoctor-color
    - asciidoctor-extension-interactive-runner
    - '@djencks/asciidoctor-mathjax'
    # FIXME Error: No protocol method ICounted.-count defined for type object:
    # <Asciidoctor::Extensions::Registry:0x44e>
    # - bytefield-svg
    # FIXME needs twitter app ID and secret
    # - asciidoctor-tweet
  attributes:
    kroki-fetch-diagram: true
    icons: font
    plantuml-server-url: 'http://www.plantuml.com/plantuml'
    experimental: ''


ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    # url: https://github.com/decidim/documentation-antora-ui/releases/download/v0.2/ui-bundle.zip
    snapshot: true
  supplemental_files: './supplemental_ui'
  # supplemental_files:
  #   - path: ui.yml
  #     contents: |
  #       static_files: [ .nojekyll ]
  #   - path: .nojekyll

output:
  clean: true
  dir: ./docs
  # destinations:
  # - provider: archive
  #   path: ./docs/distzip.zip

# https://gitlab.com/antora/docs.antora.org/-/blob/master/antora-playbook.yml