site:
  title: Log Book
  # url: https://avimehenwal.github.io/logbook/
  url: https://localhost:8080
  # start_page: work_log::index.adoc
  start_page: sample::chapter_1.adoc

content:
  sources:
  - url: .
    branches: develop
    start_path: sample
  - url: .
    branches: develop
    start_path: worklog

asciidoc:
  # javascript modules
  extensions:
    - asciidoctor-plantuml
    - asciidoctor-kroki
    - asciidoctor-chart
    - asciidoctor-emoji
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml'
    experimental: ''


ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    # url: https://github.com/decidim/documentation-antora-ui/releases/download/v0.2/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui

output:
  clean: true
  dir: ./dist
  destinations:
  - provider: archive
    path: ./dist/distzip.zip

# site:
#   title: Antora Docs
#   url: https://docs.demo.com
#   start_page: index.adoc
#   robots: allow
#   keys:
#     google_analytics: XX-123456

# content:
#   sources:
#   - url: ./modules
#   - start_path: ROOT
#   - branches: HEAD


# ui:
#   bundle:
#     url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
#     snapshot: true

# asciidoc:
#   attributes:
#     table-caption: ~
#   extensions:
#   # - asciidoctor-emoji-macro
#   - asciidoctor-kroki

# https://gitlab.com/antora/docs.antora.org/-/blob/master/antora-playbook.yml